https://travis-ci.com/PandaFoss/Awesome-Arch,,https://github.com/PandaFoss/Awesome-Arch#readme,Arch-based Projects error: <HTTPError 404: 'Not Found'> | reason: Not Found
https://telesto.ai,Nandor Magyar,https://github.com/PandaFoss/Awesome-Arch#readme,Arch-based Projects error: URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)')) | reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1123)
https://talkingarch.tk/,TalkingArch,https://github.com/PandaFoss/Awesome-Arch#readme,Arch-based Projects error: URLError(SSLCertVerificationError(1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'talkingarch.tk'. (_ssl.c:1123)")) | reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'talkingarch.tk'. (_ssl.c:1123)
https://ar.linkedin.com/in/ulisesjcf,Ulises Jeremias Cornejo Fandos,https://github.com/PandaFoss/Awesome-Arch#readme,Arch-based Projects error: <HTTPError 999: 'Request denied'> | reason: Request denied
https://xyne.archlinux.ca/projects/pbget/,pbget,https://github.com/PandaFoss/Awesome-Arch#readme,Arch-based Projects error: URLError(gaierror(8, 'nodename nor servname provided, or not known')) | reason: [Errno 8] nodename nor servname provided, or not known
https://xyne.archlinux.ca/projects/bauerbill/,Bauerbill,https://github.com/PandaFoss/Awesome-Arch#readme,Arch-based Projects error: URLError(gaierror(8, 'nodename nor servname provided, or not known')) | reason: [Errno 8] nodename nor servname provided, or not known
https://www.xferience.org/,Arch XFerience,https://github.com/PandaFoss/Awesome-Arch#readme,Arch-based Projects error: URLError(ConnectionRefusedError(61, 'Connection refused')) | reason: [Errno 61] Connection refused
https://xyne.archlinux.ca/projects/python3-aur,python3-aur,https://github.com/PandaFoss/Awesome-Arch#readme,Arch-based Projects error: URLError(gaierror(8, 'nodename nor servname provided, or not known')) | reason: [Errno 8] nodename nor servname provided, or not known